# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('slack_id', models.CharField(max_length=32)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
